import { aiService } from '@/lib/ai/service'
import { selectModel } from '@/lib/ai/router'
import { createJob, startJob, completeJob, failJob } from '@/lib/ai/jobs'
import { recordUsage } from '@/lib/ai/usage'
import { logger } from '@/lib/logging'
import type { AIContentPart } from '@/types/ai'
import {
  assetClassificationSchema,
  assetSpecExtractionSchema,
  assetIntelligenceSummarySchema,
  imageAnalysisSchema,
  documentExtractionSchema,
  type AssetIntelligenceSummaryOutput,
  type ImageAnalysisOutput,
  type DocumentExtractionOutput,
} from '@/lib/ai/schemas'

// ─── Asset Intelligence Pipeline ──────────────────────────────────────────────
//
// A stateless, composable pipeline that takes raw asset input and returns
// a validated, structured intelligence result.
//
// Stages:
//   INPUT → NORMALISE → CLASSIFY → EXTRACT → VALIDATE → CONFIDENCE → OUTPUT
//
// Key principles:
//   - AI confidence ≠ data verification state. These are ALWAYS separate.
//   - cannotIdentify: true is a valid, expected output — never manufacture data.
//   - All AI outputs are flagged requiresReview = true. Always.
//   - The pipeline never writes to the DB — callers are responsible for persistence.

// DataStatus maps to the DB enum: VERIFIED | PROVISIONAL | CALCULATED | USER_PROVIDED | UNKNOWN
// VERIFIED   = confirmed by document or human review
// PROVISIONAL = provided by user, not yet verified
// CALCULATED  = AI-inferred or logically derived
// USER_PROVIDED = entered directly by user, not AI
// UNKNOWN    = insufficient data to determine
export type DataStatus = 'VERIFIED' | 'PROVISIONAL' | 'CALCULATED' | 'USER_PROVIDED' | 'UNKNOWN'

export interface TextInput {
  kind: 'text'
  description:  string
  manufacturer?: string
  model?:        string
  year?:         number
  assetType?:    string
  serialNumber?: string
}

export interface ImageInput {
  kind:        'image'
  base64Data:  string
  mimeType:    'image/jpeg' | 'image/png' | 'image/webp'
  description?: string  // optional human hint
}

export interface DocumentInput {
  kind:     'document'
  textContent: string   // extracted text — caller handles file reading
  filename?: string
}

export type PipelineInput = TextInput | ImageInput | DocumentInput

export interface PipelineResult {
  success:     boolean
  dataStatus:  DataStatus
  confidence:  number            // 0–1
  requiresReview: boolean        // always true for AI outputs
  jobId:       string

  // Populated for text/image/document
  classification?: {
    category:    string
    assetType:   string
    confidence:  number
    isNew:       boolean
    condition:   string
  }
  specExtraction?: {
    manufacturer?:    string
    model?:           string
    variant?:         string
    yearOfManufacture?: number
    serialNumber?:    string
    specifications:   Record<string, string>
    missingFields:    string[]
    confidence:       number
  }
  imageSummary?:    ImageAnalysisOutput
  docExtraction?:  DocumentExtractionOutput
  intelligenceSummary?: AssetIntelligenceSummaryOutput

  error?:      string
  disclaimer:  string
}

// ─── Main pipeline entry point ────────────────────────────────────────────────

export async function runAssetIntelligence(input: PipelineInput): Promise<PipelineResult> {
  const disclaimer =
    'This analysis was generated by AI. All outputs are indicative and require human review. No information should be treated as verified without supporting documentation or physical inspection.'

  const job = await createJob({
    jobType:    input.kind === 'image' ? 'IMAGE_ANALYSIS' : input.kind === 'document' ? 'DOCUMENT_EXTRACTION' : 'ASSET_CLASSIFICATION',
    entityType: 'asset',
    provider:   'openai',
    model:      selectModel(input.kind === 'image' ? 'IMAGE_ANALYSIS' : input.kind === 'document' ? 'DOCUMENT_EXTRACTION' : 'SPEC_EXTRACTION').model,
  })

  await startJob(job.id)

  try {
    let result: PipelineResult

    if (input.kind === 'text') {
      result = await runTextPipeline(input, job.id, disclaimer)
    } else if (input.kind === 'image') {
      result = await runImagePipeline(input, job.id, disclaimer)
    } else {
      result = await runDocumentPipeline(input, job.id, disclaimer)
    }

    await completeJob(job.id, {
      confidence: result.confidence,
      outputSummary: `status=${result.dataStatus}, confidence=${result.confidence.toFixed(2)}`,
    })

    return result
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err)
    await failJob(job.id, msg)
    logger.warn('Asset intelligence pipeline failed', { jobId: job.id, error: msg }, 'ai')
    return {
      success: false,
      dataStatus: 'UNKNOWN',
      confidence: 0,
      requiresReview: true,
      jobId: job.id,
      error: 'The intelligence pipeline encountered an error. Please try again.',
      disclaimer,
    }
  }
}

// ─── Text pipeline ────────────────────────────────────────────────────────────

async function runTextPipeline(input: TextInput, jobId: string, disclaimer: string): Promise<PipelineResult> {
  const classifyModel = selectModel('TEXT_CLASSIFICATION')
  const extractModel  = selectModel('SPEC_EXTRACTION')

  const contextParts = [
    `Description: ${input.description}`,
    input.manufacturer ? `Manufacturer: ${input.manufacturer}` : '',
    input.model        ? `Model: ${input.model}`               : '',
    input.year         ? `Year: ${input.year}`                 : '',
    input.assetType    ? `Asset type: ${input.assetType}`      : '',
    input.serialNumber ? `Serial: ${input.serialNumber}`       : '',
  ].filter(Boolean).join('\n')

  // Stage 1: Classify
  const classifyResult = await aiService.structured({
    model:       classifyModel.model,
    temperature: classifyModel.temperature,
    systemPrompt: 'You classify business assets for a UK asset finance marketplace. State only what is known — do not infer manufacturer or model if not provided. Be explicit when information is insufficient.',
    messages:    [{ role: 'user', content: contextParts }],
    schema:      assetClassificationSchema,
    schemaName:  'AssetClassification',
  })

  if (classifyResult?.usage) {
    recordUsage({ provider: 'openai', model: classifyModel.model, jobType: 'ASSET_CLASSIFICATION', jobId, promptTokens: classifyResult.usage.promptTokens, completionTokens: classifyResult.usage.completionTokens })
  }

  // Stage 2: Extract spec
  const extractResult = await aiService.structured({
    model:       extractModel.model,
    temperature: extractModel.temperature,
    systemPrompt: 'Extract structured asset specifications from the input. Mark each field as PROVIDED (explicitly given), INFERRED (logically deducible), or UNKNOWN (cannot determine). Do not guess manufacturer or model beyond what is stated.',
    messages:    [{ role: 'user', content: contextParts }],
    schema:      assetSpecExtractionSchema,
    schemaName:  'AssetSpecExtraction',
  })

  if (extractResult?.usage) {
    recordUsage({ provider: 'openai', model: extractModel.model, jobType: 'ASSET_CLASSIFICATION', jobId, promptTokens: extractResult.usage.promptTokens, completionTokens: extractResult.usage.completionTokens })
  }

  // Stage 3: Intelligence summary
  const summaryPrompt = `
Asset input:
${contextParts}

Classification result:
Category: ${classifyResult?.result?.category ?? 'UNKNOWN'}
Asset type: ${classifyResult?.result?.assetType ?? 'UNKNOWN'}
Condition: ${classifyResult?.result?.estimatedCondition ?? 'UNKNOWN'}

Spec extraction:
Manufacturer: ${extractResult?.result?.manufacturer ?? 'not provided'}
Model: ${extractResult?.result?.model ?? 'not provided'}
Year: ${extractResult?.result?.yearOfManufacture ?? 'not provided'}
Serial: ${extractResult?.result?.serialNumber ?? 'not provided'}

Produce a structured intelligence summary distinguishing what was confirmed from the input versus what was inferred by AI versus what is genuinely unknown. Be explicit about uncertainty.`.trim()

  const summaryResult = await aiService.structured({
    model:       extractModel.model,
    temperature: 0.1,
    systemPrompt: 'You produce structured asset intelligence summaries for a UK finance marketplace. Be precise about the distinction between CONFIRMED (from input), INFERRED (AI reasoning), and MISSING. Never claim certainty that is not supported by the input.',
    messages:    [{ role: 'user', content: summaryPrompt }],
    schema:      assetIntelligenceSummarySchema,
    schemaName:  'AssetIntelligenceSummary',
  })

  const classification = classifyResult?.result
  const spec           = extractResult?.result
  const summary        = summaryResult?.result

  const confidence = summary?.overallConfidence ?? classification?.categoryConfidence ?? 0
  const dataStatus: DataStatus = confidence > 0.8 ? 'PROVISIONAL' : confidence > 0.5 ? 'CALCULATED' : 'UNKNOWN'

  return {
    success:    true,
    dataStatus,
    confidence,
    requiresReview: true,
    jobId,
    classification: classification ? {
      category:   classification.category,
      assetType:  classification.assetType,
      confidence: classification.categoryConfidence,
      isNew:      classification.isNewAsset,
      condition:  classification.estimatedCondition,
    } : undefined,
    specExtraction: spec ? {
      manufacturer:     spec.manufacturer,
      model:            spec.model,
      variant:          spec.variant,
      yearOfManufacture: spec.yearOfManufacture,
      serialNumber:     spec.serialNumber,
      specifications:   spec.specifications,
      missingFields:    spec.missingInformation,
      confidence:       spec.confidence,
    } : undefined,
    intelligenceSummary: summary ?? undefined,
    disclaimer,
  }
}

// ─── Image pipeline ───────────────────────────────────────────────────────────

async function runImagePipeline(input: ImageInput, jobId: string, disclaimer: string): Promise<PipelineResult> {
  const modelConfig = selectModel('IMAGE_ANALYSIS')

  const promptParts = [
    'Analyse this image of a business asset.',
    input.description ? `The user describes it as: ${input.description}` : '',
    'Identify what you can observe directly from the image.',
    'If you cannot reliably identify the manufacturer or model, set cannotIdentify to true — this is the correct and expected response.',
    'Do not guess or manufacture a specific model identification from an ambiguous image.',
  ].filter(Boolean).join(' ')

  // Build vision message with base64 image
  const imageUrl = `data:${input.mimeType};base64,${input.base64Data}`

  const result = await aiService.structured({
    model:       modelConfig.model,
    temperature: modelConfig.temperature,
    systemPrompt: 'You analyse images of business equipment for a UK asset finance marketplace. Only state what is directly observable. Set cannotIdentify: true when reliable identification is not possible — this is always preferable to guessing.',
    messages: [{
      role: 'user',
      content: [
        { type: 'text' as const,       text: promptParts },
        { type: 'image_url' as const,  image_url: { url: imageUrl, detail: 'high' } },
      ] as AIContentPart[],
    }],
    schema:     imageAnalysisSchema,
    schemaName: 'ImageAnalysis',
  })

  if (result?.usage) {
    recordUsage({ provider: 'openai', model: modelConfig.model, jobType: 'IMAGE_ANALYSIS', jobId, promptTokens: result.usage.promptTokens, completionTokens: result.usage.completionTokens })
  }

  const analysis = result?.result
  const confidence = analysis?.confidence ?? 0
  const dataStatus: DataStatus = analysis?.cannotIdentify ? 'UNKNOWN' : confidence > 0.7 ? 'CALCULATED' : 'UNKNOWN'

  return {
    success:      true,
    dataStatus,
    confidence,
    requiresReview: true,
    jobId,
    imageSummary: analysis ?? undefined,
    disclaimer,
  }
}

// ─── Document pipeline ────────────────────────────────────────────────────────

async function runDocumentPipeline(input: DocumentInput, jobId: string, disclaimer: string): Promise<PipelineResult> {
  const modelConfig = selectModel('DOCUMENT_EXTRACTION')

  const prompt = [
    input.filename ? `Document: ${input.filename}` : '',
    '',
    'Document content:',
    input.textContent.slice(0, 6000), // Limit to avoid excessive token usage
  ].filter((s) => s !== undefined).join('\n')

  const result = await aiService.structured({
    model:       modelConfig.model,
    temperature: modelConfig.temperature,
    systemPrompt: 'You extract structured asset and financial information from business documents for a UK asset finance marketplace. Extract only what is explicitly stated in the document. Mark each field with a confidence score. Note: document authenticity is NOT verified by this process.',
    messages:    [{ role: 'user', content: prompt }],
    schema:      documentExtractionSchema,
    schemaName:  'DocumentExtraction',
  })

  if (result?.usage) {
    recordUsage({ provider: 'openai', model: modelConfig.model, jobType: 'DOCUMENT_EXTRACTION', jobId, promptTokens: result.usage.promptTokens, completionTokens: result.usage.completionTokens })
  }

  const extraction = result?.result
  const confidence = extraction?.overallConfidence ?? 0
  const dataStatus: DataStatus = confidence > 0.8 ? 'PROVISIONAL' : confidence > 0.5 ? 'CALCULATED' : 'UNKNOWN'

  return {
    success:       true,
    dataStatus,
    confidence,
    requiresReview: true,
    jobId,
    docExtraction: extraction ?? undefined,
    disclaimer,
  }
}
